name: FishInControl
version: '${project.version}'
main: net.fishport.fishincontrol.FishInControl
api-version: '1.20'
folia-supported: true

#libraries:
#  - net.kyori:adventure-api:4.17.0
#  - net.kyori:adventure-text-minimessage:4.17.0

commands:
  fishincontrol:
    aliases: [fic]
    usage: /<command> reload
    permission: fishincontrol.admin

permissions:
  fishincontrol.admin:
    description: Allows reloading config file with /fishincontrol reload.
    default: op

  fishincontrol.bypass:
    description: Bypass item replacement.
    default: false

  fishincontrol.forced:
    description: forced item replacement.
    default: false